### ISSUE TITLE
OpenAPI 3.0.0-RC0 validity

### ISSUE THREAD

**Issue by MikeRalphson** [pjmolina/event-backend#1] opened 2017-03-08 11:25 UTC
Hi @pjmolina (Mike - @ PermittedSoc on Twitter) here,

I've been following your projects with keen interest, as I am writing a [converter](https://github.com/mermade/swagger2openapi) (and validator) for Swagger 2.0 to OpenAPI 3.0.x.

I'm not sure if this is the right project to raise an issue on, and even if so, the error may be in my validator or my reading of the OpenAPI Specification.

There is a hosted version of the validator tool [here](https://openapi-converter.herokuapp.com/) which has an API for validating OpenAPI 3.0.x specs.

The result of running against your spec is [as reported here](https://openapi-converter.herokuapp.com/api/v1/validate?url=https://openapi3.herokuapp.com/api/openapi.json) (first error only):

````json
{"status":false,"message":"Parameter type body is no-longer valid"}
````

The validator also has badge functionality, so it currently shows

![Badge](https://openapi-converter.herokuapp.com/api/v1/badge?url=https://openapi3.herokuapp.com/api/openapi.json)

I have tried converting your 2.0 spec and comparing my output to your 3.0.0 spec but I think the two files were generated by different tools?

Keen to hear your thoughts.

**Comment by pjmolina** [comment] 2017-03-08 15:07
Hi Mike!

Thanks for taking the time to testing it!
I will investigate it and try to locate the root cause. 
Thanks for sharing a validator for v.3. This definitely will help to test and fix issues faster.

The v.3 contract in this project is generated by reflection on the services exposed. If there is a bug in the generator (most likely), I will forward the bug to the right project [baucis-openapi3](https://github.com/metadevpro/baucis-openapi3) and close this issue here.

**Comment by pjmolina** [comment] 2017-03-08 15:29
Confirmed. Moved to [baucis-openapi3/issues#1](https://github.com/metadevpro/baucis-openapi3/issues/1) for a fix and closing here.

**Closed by pjmolina** 2017-03-08 15:29 UTC
